export const COURSE_MODULE_ITEMS_FETCH = 'COURSE_MODULE_ITEMS_FETCH'
export const COURSE_MODULE_ITEMS_FETCH_SUCCESS =
  'COURSE_MODULE_ITEMS_FETCH_SUCCESS'
export const COURSE_MODULE_ITEMS_FETCH_FAILURE =
  'COURSE_MODULE_ITEMS_FETCH_FAILURE'
export const COURSE_MODULE_ITEMS_FETCH_CANCEL =
  'COURSE_MODULE_ITEMS_FETCH_CANCEL'

export const COURSE_MODULE_ITEMS_BULK_INSERT = 'COURSE_MODULE_ITEMS_BULK_INSERT'
