export const COURSE_RECORDINGS_FETCH = 'COURSE_RECORDINGS_FETCH'
export const COURSE_RECORDINGS_FETCH_SUCCESS = 'COURSE_RECORDINGS_FETCH_SUCCESS'
export const COURSE_RECORDINGS_FETCH_FAILURE = 'COURSE_RECORDINGS_FETCH_FAILURE'
export const COURSE_RECORDINGS_FETCH_CANCEL = 'COURSE_RECORDINGS_FETCH_CANCEL'
