export const PROGRAM_FETCH = 'PROGRAM_FETCH'
export const PROGRAM_FETCH_SUCCESS = 'PROGRAM_FETCH_SUCCESS'
export const PROGRAM_FETCH_CANCEL = 'PROGRAM_FETCH_CANCEL'
export const PROGRAM_FETCH_FAILURE = 'PROGRAM_FETCH_FAILURE'
