export const COURSE_MODULES_FETCH = 'COURSE_MODULES_FETCH'
export const COURSE_MODULES_FETCH_SUCCESS = 'COURSE_MODULES_FETCH_SUCCESS'
export const COURSE_MODULES_FETCH_FAILURE = 'COURSE_MODULES_FETCH_FAILURE'
export const COURSE_MODULES_FETCH_CANCEL = 'COURSE_MODULES_FETCH_CANCEL'
