export const COURSE_ITEM_CONTENT_FETCH = 'COURSE_ITEM_CONTENT_FETCH'
export const COURSE_ITEM_CONTENT_FETCH_SUCCESS =
  'COURSE_ITEM_CONTENT_FETCH_SUCCESS'
export const COURSE_ITEM_CONTENT_FETCH_FAILURE =
  'COURSE_ITEM_CONTENT_FETCH_FAILURE'
export const COURSE_ITEM_CONTENT_FETCH_CANCEL =
  'COURSE_ITEM_CONTENT_FETCH_CANCEL'
