export const COURSE_GRADES_FETCH = 'COURSE_GRADES_FETCH'
export const COURSE_GRADES_FETCH_SUCCESS = 'COURSE_GRADES_FETCH_SUCCESS'
export const COURSE_GRADES_FETCH_FAILURE = 'COURSE_GRADES_FETCH_FAILURE'
export const COURSE_GRADES_FETCH_CANCEL = 'COURSE_GRADES_FETCH_CANCEL'
